### ISSUE TITLE
Code recast

### ISSUE THREAD

**Issue by GabrielCogne** [danlux18/DSL-Kisled-AI#2]
### Changes in the syntax:
⚠️ In some syntactic cases, parentheses are mandatory. If parentheses are not mandatory, the illustrations below omit them.

#### Data acquistion
Use `read` method to read an input file and put it in a variable
```groovy
read ( path ) >> variable
```

#### Select operation
Select a sub part of a set or dataframe and put it in a variable
```groovy
varname[selection] >> varname
```
##### Selection
Selection can be done using range object and it is possible to use more than one
```groovy
// Each parameter are optionnal
r(start, stop, step)
```
Exemples:
```groovy
set[0]                                      // First element of the set
set["first"]                               // Elements under key "first"
set[r()]                                     // All set
set[r(stop: 2)]                           // The two first elements of the set
matrix[r(), r(stop: 10, step: 2)]   //  All columns but only even rows in the first 10
```

#### Apply operation
The Apply operation can be used to normalise the data in a dataframe. They consist of the basic operations plus, minus, multiplication, power and division.
```groovy
varname op value >> varname
```
Exemples:
```groovy
dataframe1 + 1 >> dataframe2
dataframe1 - 10 >> dataframe3
dataframe2 * 0.5 >> dataframe4
dataframe3 / 255 >> dataframe5
```

#### Drop column operation
Select all data in a dataframe except for a named column. 
```groovy
dataframe1 - "column_name" >> dataframe2
dataframe1 - ["column1", "column3"] >> dataframe1
```

#### Mapping operation
Change value in a Dataframe using a map
```groovy
input_dataframe >> ["key": value] >> output_dataframe
```

### Todo list
- [x] Change data acquisition process
- [x] Change Data operations: data selection
- [x] Change Data operations: apply function on data
- [x] Change Data operations: delete column
- [x] Change Data operations: data mapping
